# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Data Science Training for Librarians 
subtitle: "#DST4L"
email: jeek@dtu.dk
name: Jeannette EkstrÃ¸m
#  Write an awesome description for your new site here. You can edit this
#  line in _config.yml. It will appear in your document head meta (for
#  Google search results) and in your feed.xml site description.
description: >
  Data Science Training for Librarians.
# Base URL of site (i.e. /blog). It should always start with a slash,
# and never end with a slash. Set it to a blank value if hosting at the
# root of your server.
#baseurl: "{{site.github.url}}" # the subpath of your site, e.g. /blog/
url: "http://dst4l.github.io" # the base hostname & protocol for your site
cover: "/img/DTUrunway.jpg"
twitter_username: dst4l
github_username:  dst4l

# Build settings
markdown: kramdown
#theme: minima
#

# Collections : (see http://jekyllrb.com/docs/collections/)

collections:
  speakers:
      output: true

defaults:
  -
    scope:
      path: ""
      type: "speakers"
    values:
      layout: "speaker"
      image: "speaker.gif"
      role: "Speaker"

